before_script:
  - curl --silent --show-error https://getcomposer.org/installer | php
  - php composer.phar install
  - bash _ci/docker_install.sh > /dev/null

test:5.6:
  image: php:5.6
  script:
  - /usr/local/bin/phpunit --configuration phpunit.xml.dist

test:7.0:
  image: php:7.0
  script:
  - /usr/local/bin/phpunit --configuration phpunit.xml.dist