stages:
 - test
 - build
 - performances
 - deploy

# =================================================================================================
# Test environment
# =====
# Used to test the classes and unit phase).
# =================================================================================================
test:5.6:
 stage: test
 image: php:5.6
 before_script:
  - curl --silent --show-error https://getcomposer.org/installer | php
  - php composer.phar install
  - bash _ci/docker_install.sh > /dev/null
 script:
  - phpunit --configuration phpunit.xml.dist

 test:7.0:
  image: php:7.0
  before_script:
   - curl --silent --show-error https://getcomposer.org/installer | php
   - php composer.phar install
   - bash _ci/docker_install.sh > /dev/null
  script:
  - phpunit --configuration phpunit.xml.dist

# =================================================================================================
# Build phase
# =====
# Used to build the code and check if this last one can be used into "functional" application.
# =================================================================================================
build:
 stage: build
 before_script:
  - curl --silent --show-error https://getcomposer.org/installer | php
  - php composer.phar install
  - bash _ci/docker_install.sh > /dev/null

# =================================================================================================
# Performances phase
# =====
# Used to test the performances using Blackfire.
# =================================================================================================
performances:
 stage: performances

# =================================================================================================
# Deploy phase
# =====
# Used if every stages is green and all the code are covered.
# =================================================================================================
deploy:
 stage: deploy

