before_script:
  - curl --silent --show-error https://getcomposer.org/installer | php
  - php composer.phar install
  - bash _ci/docker_install.sh > /dev/null

test:7.0:
  image: php:7.0
  script:
  - phpunit --configuration phpunit.xml.dist