home:
   path:    /
   methods: 'GET'
   defaults: { _controller: AppBundle:Web/Home:index }

blog:
    path:    /blog
    methods: 'GET'
    defaults: { _controller: AppBundle:Web/Home:blog }

creations:
    path:    /creations
    methods: 'GET'
    defaults: { _controller: AppBundle:Web/Home:creations }

about:
    path:    /about
    methods: 'GET'
    defaults: { _controller: AppBundle:Web/Home:about }

formations:
    path:    /formations
    methods: 'GET'
    defaults: { _controller: AppBundle:Web/Home:formation }

contact:
    path:    /contact
    methods: 'GET'
    defaults: { _controller: AppBundle:Web/Home:contact }
