AppBundle\Entity\Category:
    type: entity
    table: guillaumeloulier_category
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            lenght: 100
            nullable: false
    oneToMany:
        article:
            targetEntity: AppBundle\Entity\Article
            mappedBy: category