AppBundle\Entity\Tags:
    type: entity
    table: guillaumeloulier_tags
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 200
    manyToOne:
        category:
            targetEntity: AppBundle\Entity\Article
            inversedBy: tags
            joinColumn:
                name: article_id
                referencedColumnName: id